---
:concurrency: 5
:timeout: 30
:verbose: false
:queues:
  - default
  - mailers
  - ahoy

# Production configuration
:production:
  :concurrency: 10
  :timeout: 30

# Development configuration
:development:
  :concurrency: 2
  :timeout: 30
  :verbose: true

# Test configuration
:test:
  :concurrency: 1
  :timeout: 5
