name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  CI: true

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Scan for security vulnerabilities in Ruby dependencies
        run: bin/bundle-audit check --update

  scan_js:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: yarn audit --level moderate

  lint:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate JS routes
        run: bundle exec rake js:routes

      - name: Check for uncommitted changes
        run: |
          if ! git diff --exit-code; then
            echo "::error file=app/frontend/lib/routes.js::Detected changes in generated JS routes. Run 'bundle exec rake js:routes' and commit the result."
            exit 1
          fi

      - name: Build TypeScript
        run: yarn build

      - name: Check formatting with Prettier
        run: yarn prettier --check .

      - name: Typecheck
        run: yarn tsc --noEmit

      - name: Lint Ruby with Rubocop
        run: bundle exec rubocop -f github

      - name: Lint JavaScript/TypeScript with ESLint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Generate JS routes
        run: bundle exec rake js:routes

      - name: Build Vite assets
        run: yarn build

      - name: Run tests
        run: bin/rails db:test:prepare test test:system
        env:
          RAILS_ENV: test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
